project_name: centralized-relay
env:
  - CGO_ENABLED=1
builds:
  - id: amd64
    main: ./main.go
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.x86_64.a -P /usr/lib/x86_64-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/centralized-relay/relayer.Version={{ .Tag }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -lm'
    tags:
      - muslc
      - netgo
  - id: arm64
    main: ./main.go
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.aarch64.a -P /usr/lib/aarch64-linux-gnu
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/centralized-relay/relayer.Version={{ .Tag }}
      - -linkmode=external
      - -extldflags "-static"
      - -extldflags '-Wl,-z,muldefs -lm'
    tags:
      - muslc
      - netgo

dockers:
  - image_templates:
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-amd64
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-latest-amd64
    dockerfile: goreleaser.dockerfile
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-arm64v8
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-latest-arm64v8
    dockerfile: goreleaser.dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: iconcommunity/{{.ProjectName}}:latest
    image_templates:
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-latest-amd64
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-latest-arm64v8
  - name_template: iconcommunity/{{.ProjectName}}:{{ .Tag }}
    image_templates:
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-amd64
      - iconcommunity/{{.ProjectName}}:{{ .Tag }}-arm64v8

archives:
  - id: golang-cross
    builds:
      - amd64
      - arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  draft: true
