# playbook.yml
- hosts: localhost
  # connection: local
  # gather_facts: False
  # become_method: sudo
  gather_facts: no
  become: no
  vars:
    ansible_ssh_private_key_file: "./my_aws_key"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - centralized-relay-ansible
